//Java imports
package lib.ui.MainPage;

//Proyect imports
import javax.swing.JLabel;
import lib.utils.AppColors;

public class MainPageView extends javax.swing.JPanel {
    private final AppColors colors = new AppColors();

    public MainPageView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SendDataButton = new javax.swing.JLabel();
        TestButton = new javax.swing.JLabel();
        ShowDataButton = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(960, 540));
        setMinimumSize(new java.awt.Dimension(960, 540));

        SendDataButton.setBackground(this.colors.buttonsColor());
        SendDataButton.setFont(new java.awt.Font("Leelawadee UI", 0, 16)); // NOI18N
        SendDataButton.setForeground(this.colors.textButtonsColor());
        SendDataButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SendDataButton.setText("Enviar Datos");
        SendDataButton.setOpaque(true);

        TestButton.setBackground(this.colors.buttonsColor());
        TestButton.setFont(new java.awt.Font("Leelawadee UI", 0, 16)); // NOI18N
        TestButton.setForeground(this.colors.textButtonsColor());
        TestButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TestButton.setText("Procesar Datos");
        TestButton.setOpaque(true);

        ShowDataButton.setBackground(this.colors.buttonsColor());
        ShowDataButton.setFont(new java.awt.Font("Leelawadee UI", 0, 16)); // NOI18N
        ShowDataButton.setForeground(this.colors.textButtonsColor());
        ShowDataButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ShowDataButton.setText("Mostrar Datos");
        ShowDataButton.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(175, 175, 175)
                .addComponent(SendDataButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80)
                .addComponent(ShowDataButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80)
                .addComponent(TestButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(175, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(454, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SendDataButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ShowDataButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TestButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56))
        );
    }// </editor-fold>//GEN-END:initComponents

    protected JLabel getSendDataButton() {return this.SendDataButton;}
    protected JLabel getShowDataButton() {return this.ShowDataButton;}
    protected JLabel getTestButton() {return this.TestButton;}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel SendDataButton;
    private javax.swing.JLabel ShowDataButton;
    private javax.swing.JLabel TestButton;
    // End of variables declaration//GEN-END:variables
}
