//Java imports
package lib.ui.SendData;

//Proyect imports
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JTextField;
import lib.models.InformationModel;
import lib.utils.AppColors;

public class SendDataView extends javax.swing.JPanel {
    private AppColors colors = new AppColors();

    public SendDataView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backButton = new javax.swing.JLabel();
        sensorTitle = new javax.swing.JLabel();
        titleSeparator = new javax.swing.JSeparator();
        sensorPanel = new javax.swing.JPanel();
        nameField = new javax.swing.JTextField();
        typeLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        namesList = new javax.swing.JComboBox<>();
        minimumLabel = new javax.swing.JLabel();
        locationField = new javax.swing.JTextField();
        MinimumLabel = new javax.swing.JLabel();
        locationLabel = new javax.swing.JLabel();
        averageField = new javax.swing.JTextField();
        typeField = new javax.swing.JTextField();
        minimumField = new javax.swing.JTextField();
        maximumField = new javax.swing.JTextField();
        averageLabel = new javax.swing.JLabel();
        hourNumberField = new javax.swing.JTextField();
        hourNumberLabel = new javax.swing.JLabel();
        sensorHistoryTitle = new javax.swing.JLabel();
        titleSeparator_2 = new javax.swing.JSeparator();
        historyPanel = new javax.swing.JPanel();
        valueField = new javax.swing.JTextField();
        valueLabel = new javax.swing.JLabel();
        dateTimeField = new javax.swing.JTextField();
        dateTimeLabel = new javax.swing.JLabel();
        processingField = new javax.swing.JTextField();
        processingLabel = new javax.swing.JLabel();
        SendButton = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(960, 540));
        setMinimumSize(new java.awt.Dimension(960, 540));

        backButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lib/images/BackButton_38x38px.png"))); // NOI18N

        sensorTitle.setFont(new java.awt.Font("Leelawadee UI", 0, 16)); // NOI18N
        sensorTitle.setForeground(colors.textColor());
        sensorTitle.setText("Sensor");

        sensorPanel.setBackground(new java.awt.Color(245, 245, 245));

        nameField.setFont(new java.awt.Font("Leelawadee UI", 0, 16)); // NOI18N
        nameField.setForeground(colors.textColor());
        nameField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        typeLabel.setFont(new java.awt.Font("Leelawadee UI", 0, 16)); // NOI18N
        typeLabel.setForeground(colors.textColor());
        typeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        typeLabel.setText("Tipo Sensor");

        nameLabel.setFont(new java.awt.Font("Leelawadee UI", 0, 16)); // NOI18N
        nameLabel.setForeground(colors.textColor());
        nameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nameLabel.setText("Nombre sensor");

        namesList.setBackground(new java.awt.Color(245, 245, 245));
        namesList.setFont(new java.awt.Font("Leelawadee UI", 0, 16)); // NOI18N
        namesList.setForeground(colors.textColor());
        namesList.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        minimumLabel.setFont(new java.awt.Font("Leelawadee UI", 0, 16)); // NOI18N
        minimumLabel.setForeground(colors.textColor());
        minimumLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        minimumLabel.setText("Valor Maximo");

        locationField.setFont(new java.awt.Font("Leelawadee UI", 0, 16)); // NOI18N
        locationField.setForeground(colors.textColor());
        locationField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        MinimumLabel.setFont(new java.awt.Font("Leelawadee UI", 0, 16)); // NOI18N
        MinimumLabel.setForeground(colors.textColor());
        MinimumLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MinimumLabel.setText("Valor Minimo");

        locationLabel.setFont(new java.awt.Font("Leelawadee UI", 0, 16)); // NOI18N
        locationLabel.setForeground(colors.textColor());
        locationLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        locationLabel.setText("Ubicación sensor");

        averageField.setFont(new java.awt.Font("Leelawadee UI", 0, 16)); // NOI18N
        averageField.setForeground(colors.textColor());
        averageField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        typeField.setFont(new java.awt.Font("Leelawadee UI", 0, 16)); // NOI18N
        typeField.setForeground(colors.textColor());
        typeField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        minimumField.setFont(new java.awt.Font("Leelawadee UI", 0, 16)); // NOI18N
        minimumField.setForeground(colors.textColor());
        minimumField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        maximumField.setFont(new java.awt.Font("Leelawadee UI", 0, 16)); // NOI18N
        maximumField.setForeground(colors.textColor());
        maximumField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        averageLabel.setFont(new java.awt.Font("Leelawadee UI", 0, 16)); // NOI18N
        averageLabel.setForeground(colors.textColor());
        averageLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        averageLabel.setText("Promedio valores");

        hourNumberField.setFont(new java.awt.Font("Leelawadee UI", 0, 16)); // NOI18N
        hourNumberField.setForeground(colors.textColor());
        hourNumberField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        hourNumberLabel.setFont(new java.awt.Font("Leelawadee UI", 0, 16)); // NOI18N
        hourNumberLabel.setForeground(colors.textColor());
        hourNumberLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hourNumberLabel.setText("Número de horas");

        javax.swing.GroupLayout sensorPanelLayout = new javax.swing.GroupLayout(sensorPanel);
        sensorPanel.setLayout(sensorPanelLayout);
        sensorPanelLayout.setHorizontalGroup(
            sensorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sensorPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(namesList, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(sensorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(locationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(locationField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(sensorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(nameLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(nameField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(40, 40, 40)
                .addGroup(sensorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(averageField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(averageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(typeField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(typeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(sensorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sensorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(MinimumLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(minimumField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(hourNumberLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hourNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(sensorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(maximumField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(minimumLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        sensorPanelLayout.setVerticalGroup(
            sensorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sensorPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sensorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sensorPanelLayout.createSequentialGroup()
                        .addGroup(sensorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(typeField)
                            .addComponent(maximumField)
                            .addComponent(nameField)
                            .addComponent(namesList, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(sensorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(minimumLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(typeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(sensorPanelLayout.createSequentialGroup()
                        .addComponent(minimumField, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(MinimumLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(60, 60, 60)
                .addGroup(sensorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(averageField)
                    .addComponent(locationField)
                    .addComponent(hourNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(sensorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(averageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hourNumberLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(locationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        sensorHistoryTitle.setFont(new java.awt.Font("Leelawadee UI", 0, 16)); // NOI18N
        sensorHistoryTitle.setForeground(colors.textColor());
        sensorHistoryTitle.setText("Historico sensor");

        historyPanel.setBackground(new java.awt.Color(245, 245, 245));

        valueField.setFont(new java.awt.Font("Leelawadee UI", 0, 16)); // NOI18N
        valueField.setForeground(colors.textColor());
        valueField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        valueLabel.setFont(new java.awt.Font("Leelawadee UI", 0, 16)); // NOI18N
        valueLabel.setForeground(colors.textColor());
        valueLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        valueLabel.setText("Valor Registrado");

        dateTimeField.setEditable(false);
        dateTimeField.setFont(new java.awt.Font("Leelawadee UI", 0, 16)); // NOI18N
        dateTimeField.setForeground(colors.textColor());
        dateTimeField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        dateTimeLabel.setFont(new java.awt.Font("Leelawadee UI", 0, 16)); // NOI18N
        dateTimeLabel.setForeground(colors.textColor());
        dateTimeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dateTimeLabel.setText("Fecha y hora");

        processingField.setFont(new java.awt.Font("Leelawadee UI", 0, 16)); // NOI18N
        processingField.setForeground(colors.textColor());
        processingField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        processingLabel.setFont(new java.awt.Font("Leelawadee UI", 0, 16)); // NOI18N
        processingLabel.setForeground(colors.textColor());
        processingLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        processingLabel.setText("Procesamiento");

        javax.swing.GroupLayout historyPanelLayout = new javax.swing.GroupLayout(historyPanel);
        historyPanel.setLayout(historyPanelLayout);
        historyPanelLayout.setHorizontalGroup(
            historyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(historyPanelLayout.createSequentialGroup()
                .addGap(202, 202, 202)
                .addGroup(historyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(valueLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(valueField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(historyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dateTimeField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateTimeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(historyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(processingLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(processingField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        historyPanelLayout.setVerticalGroup(
            historyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(historyPanelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(historyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(historyPanelLayout.createSequentialGroup()
                        .addGroup(historyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(dateTimeField)
                            .addComponent(valueField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(historyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(valueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dateTimeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(historyPanelLayout.createSequentialGroup()
                        .addComponent(processingField)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(processingLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(17, 17, 17))
        );

        SendButton.setBackground(colors.buttonsColor());
        SendButton.setFont(new java.awt.Font("Leelawadee UI", 0, 16)); // NOI18N
        SendButton.setForeground(new java.awt.Color(255, 255, 255));
        SendButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SendButton.setText("Enviar Datos");
        SendButton.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(historyPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sensorPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(titleSeparator)
                            .addComponent(sensorHistoryTitle)
                            .addComponent(titleSeparator_2, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(sensorTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(backButton)
                        .addGap(16, 16, 16)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(390, 390, 390)
                .addComponent(SendButton, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(sensorTitle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(titleSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(backButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sensorPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(sensorHistoryTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(titleSeparator_2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(historyPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(SendButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );
    }// </editor-fold>//GEN-END:initComponents

    protected void setNamesOptions(String[] sensorNames){
        this.namesList.setModel(new DefaultComboBoxModel<>(sensorNames));
    }
    
    protected void setInformation(InformationModel information){
        this.nameField.setText(information.getName());
        this.typeField.setText(information.getType());
        this.minimumField.setText(information.getMinimum());
        this.maximumField.setText(information.getMaximum());
        this.locationField.setText(information.getLocation());
        this.averageField.setText(information.getAverage());
        this.hourNumberField.setText(information.getHoursNumber());
    }
    
    protected JLabel getBackButton() {return this.backButton;}
    protected JLabel getSendButton() {return this.SendButton;}
    protected JComboBox getComboBox() {return this.namesList;}
    protected JTextField getNameField() {return this.nameField;}
    protected JTextField getTypeField() {return this.typeField;}
    protected JTextField getMinimumField() {return this.minimumField;}
    protected JTextField getMaximumField() {return this.maximumField;}
    protected JTextField getLocationField() {return this.locationField;}
    protected JTextField getAverageField() {return this.averageField;}
    protected JTextField getHoursNumberField() {return this.hourNumberField;}
    protected JTextField getValueField() {return this.valueField;}
    protected JTextField getProcessingField() {return this.processingField;}
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel MinimumLabel;
    private javax.swing.JLabel SendButton;
    private javax.swing.JTextField averageField;
    private javax.swing.JLabel averageLabel;
    private javax.swing.JLabel backButton;
    private javax.swing.JTextField dateTimeField;
    private javax.swing.JLabel dateTimeLabel;
    private javax.swing.JPanel historyPanel;
    private javax.swing.JTextField hourNumberField;
    private javax.swing.JLabel hourNumberLabel;
    private javax.swing.JTextField locationField;
    private javax.swing.JLabel locationLabel;
    private javax.swing.JTextField maximumField;
    private javax.swing.JTextField minimumField;
    private javax.swing.JLabel minimumLabel;
    private javax.swing.JTextField nameField;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JComboBox<String> namesList;
    private javax.swing.JTextField processingField;
    private javax.swing.JLabel processingLabel;
    private javax.swing.JLabel sensorHistoryTitle;
    private javax.swing.JPanel sensorPanel;
    private javax.swing.JLabel sensorTitle;
    private javax.swing.JSeparator titleSeparator;
    private javax.swing.JSeparator titleSeparator_2;
    private javax.swing.JTextField typeField;
    private javax.swing.JLabel typeLabel;
    private javax.swing.JTextField valueField;
    private javax.swing.JLabel valueLabel;
    // End of variables declaration//GEN-END:variables
}
