//Java imports
package lib.ui.MainApp;

import java.awt.Component;
import javax.swing.JPanel;
import lib.ui.MainPage.MainPageView;
import lib.ui.SendData.SendDataView;
import lib.ui.ShowData.ShowDataView;
import lib.ui.Test.TestView;

public class MainAppView extends javax.swing.JFrame {

    public MainAppView() {
        initComponents();
        
        this.setSize(960, 540);
        this.setResizable(false);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(960, 540));
        setMinimumSize(new java.awt.Dimension(960, 540));
        setPreferredSize(new java.awt.Dimension(960, 540));
        getContentPane().setLayout(new java.awt.CardLayout());

        MainPanel.setBackground(new java.awt.Color(102, 255, 102));
        MainPanel.setLayout(new java.awt.CardLayout());
        getContentPane().add(MainPanel, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainAppView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainAppView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainAppView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainAppView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainAppView().setVisible(true);
            }
        });
    }
    
    public void setMainPage(MainPageView mainPageView){
        for(Component c : this.MainPanel.getComponents()){
            c.setVisible(false);
        }
        this.MainPanel.removeAll();
        this.MainPanel.add(mainPageView);
        mainPageView.setVisible(true);
    }
    
    public void setSendData(SendDataView sendDataView){
        for(Component c : this.MainPanel.getComponents()){
            c.setVisible(false);
        }
        this.MainPanel.removeAll();
        this.MainPanel.add(sendDataView);
        sendDataView.setVisible(true);
    }
    
    public void setShowData (ShowDataView showDataView){
        for(Component c : this.MainPanel.getComponents()){
            c.setVisible(false);
        }
        this.MainPanel.removeAll();
        this.MainPanel.add(showDataView);
        showDataView.setVisible(true);
    }
    
    public void setTest (TestView testView){
        for(Component c : this.MainPanel.getComponents()){
            c.setVisible(false);
        }
        this.MainPanel.removeAll();
        this.MainPanel.add(testView);
        testView.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MainPanel;
    // End of variables declaration//GEN-END:variables
}
